[insim]
host = "127.0.0.1"
port = 29999
admin = ""

[ai]
rearFogLightsOnDelay = 3000
extraLightsOffDelay = 20000
frontFogLightsOnDelayMin = 2000
frontFogLightsOnDelayMax = 2000
track = "^7NORISRING"
track2 = "^7TRACK"