[insim]
host = "127.0.0.1"
port = 29999
admin = ""
carPositionPacketInterval = 100

[general]
#pitLaneSpeedLimitKmh = 80

[ai]
rearFogLightsOnDelay = 3000
frontFogLightsOnDelayMin = 2000
frontFogLightsOnDelayMax = 2000
track = "^7NORISRING"
track2 = "^7TRACK"
track3 = "^72009"
track3BlinkTimeout = 5000

[rcm]
goMessageTimeout = 3000